### ISSUE TITLE
"multihash must be a Buffer" error

### ISSUE THREAD

**Issue by ThiniusAirington** [multiformats/js-multihash#12]
Whenever I run this code, I get an error indicating that the passed multihash isn't a buffer.

```javascript
const Base58 = require('base-58');
const multihash = require('multihashes');
const buf = Base58.decode('QmRJzsvyCQyizr73Gmms8ZRtvNxmgqumxc2KUp71dfEmoj');
multihash.decode(buf);//Throws Error: multihash must be a Buffer
```
When diving into the source, I noticed that the exports.validate function uses Buffer.isBuffer, which returns false for the multi hash in question causing the above error to be thrown. Getting rid of this check seems to produced the desired results, but I can't figure out why Buffer.isBuffer returns false.

 Any help would be appreciated?

**Comment by dignifiedquire** [comment]
Looking at the source code of [`base-58`](https://github.com/45678/Base58) it does not look to me like it is actually using `Buffer` instances for the return value. I suggest doing this

```js
const multihash = require('multihashes');
const buf = multihash.fromB58String('QmRJzsvyCQyizr73Gmms8ZRtvNxmgqumxc2KUp71dfEmoj');
```

**Comment by dignifiedquire** [comment]
And for the decoding part then of course 

```js
multihash.decode(buf);
```

**Comment by diasdavid** [comment]
We use https://www.npmjs.com/package/bs58 and it has worked well for us :)

**Comment by dignifiedquire** [comment]
Closing this, as the new api makes these things super easy without the need for using `bs58` modules directly :)

**Comment by diasdavid** [comment]
🎉🎉🎉

**Comment by jbenet** [comment]
❤️❤️❤️
