### ISSUE TITLE
Update references from move

### ISSUE THREAD

**Issue by dignifiedquire** [multiformats/js-multihash#13]
- package.json
- Readme
- Reenable CI

**Comment by RichardLitt** [comment]
Those are just in this repo, yes?

**Comment by dignifiedquire** [comment]
yea

**Comment by RichardLitt** [comment]
On it.

**Comment by RichardLitt** [comment]
Ok: David is updated, and coveralls, and travis. Not sure what is up with circle-ci. @jbenet, can you check?

**Comment by jbenet** [comment]
No sorry. I dont have time for this stuff.

**Comment by RichardLitt** [comment]
No worries.

**Comment by diasdavid** [comment]
I've activated it:)
