### ISSUE TITLE
Add keccak256 support

### ISSUE THREAD

**Issue by kumavis** [multiformats/js-multihash#20]
pending acceptance to standard and assignment of a code: https://github.com/multiformats/multihash/issues/54

**Comment by diasdavid** [comment]
code assignment done, wanna add this feature to js-multihash, js-multihashing and js-multihashing-async?

**Comment by kumavis** [comment]
yep. tracking here:
- [ ] js-multihash
- [ ] js-multihashing
- [ ] js-multihashing-async

**Comment by kumavis** [comment]
@diasdavid @dignifiedquire can you verify we need both `js-multihashing` and `js-multihashing-async` ?

**Comment by dignifiedquire** [comment]
> @diasdavid @dignifiedquire can you verify we need both js-multihashing and js-multihashing-async ?

We only use js-multihashing-async at this point, so imho there is no need to add it to js-multihashing.

**Comment by diasdavid** [comment]
I would rather keep both modules consistent with the same features. There are way more users of multihashes than just IPFS users

**Comment by dignifiedquire** [comment]
Implemented it in multihashing-async: https://github.com/multiformats/js-multihashing-async/pull/4

**Comment by kumavis** [comment]
Closing in favor of tracking here https://github.com/multiformats/js-multihashing/issues/14
