### ISSUE TITLE
Enable validate for string multihash

### ISSUE THREAD

**Issue by RichardLitt** [multiformats/js-multihash#31]
Looks like multihash.validate takes a buffer. Can it also take a string?

**Comment by diasdavid** [comment]
sure, wanna submit a PR for that?

**Comment by dignifiedquire** [comment]
i thought we were trying to avoid apis that take both?

**Comment by RichardLitt** [comment]
Why don't we make a module `is-multihash`? Seems very node.

**Comment by dignifiedquire** [comment]
I am not sure what that would do. A multihash is always a buffer, so validate works for that. Otherwise for more futureproof validation including base encoding you should use cid rather than multihash.

**Comment by RichardLitt** [comment]
`A multihash is always a buffer`

I'm not sure this is true. For instance, if I run `ipfs add file`, I get back a multihash. When I copy it into my browser, it is a string. What am I missing in this story?

**Comment by dignifiedquire** [comment]
a multihash in the js-multihash sense is always a buffer. In the general sense a multihash can be represented as a base encoded string, as that is a bit easier for humans to handle. But for that case the validate logic you are asking should be part of js-cid, ie `Cid.isCidString(mybaseencodedstring)`

**Comment by RichardLitt** [comment]
Specifically, I was asking if there was an easy way of checking isCID. Makes sense. Should that be added as syntactic sugar here? Would a module combining isCidString and .validate make sense?

**Comment by dignifiedquire** [comment]
I think adding it to js-cid makes sense. Making it its own module is going a bit too far for my taste, especially because `Cid.isCid` is already exists for checking if something is a cid object.

**Comment by diasdavid** [comment]
Yeah, @dignifiedquire is right, indeed there is no case for a multihash in string format, what you want is to check if something is a valid base58 encoded multihash or if it is a valid CID.

Valid CID is on the CID module and valid IPFS multihash in b58 encoding is available on is-ipfs.

Does this fit your needs @RichardLitt ?

**Comment by RichardLitt** [comment]
Can you explain the difference between a CID and a valid IPFS multihash in b58 encoding? I'm curious if there's some easy way for me to check if any hash is a valid IPFS hash, basically.

**Comment by diasdavid** [comment]
> I'm curious if there's some easy way for me to check if any hash is a valid IPFS hash, basically.
This is your package - https://www.npmjs.com/package/is-ipfs

**Comment by dignifiedquire** [comment]
A base58 encoded multihash is a valid cid version 0. This means, all base58 encoded multihashes are cids, but not all cids are base58 encoded multihashes

**Comment by RichardLitt** [comment]
is-ipfs is what I was looking for. Thank you.

**Comment by diasdavid** [comment]
^5 to @xicombd for making it :)
