### ISSUE TITLE
Streaming?

### ISSUE THREAD

**Issue by mikeal** [multiformats/js-multihash#35]
Heya,

The Node.js crypto libraries support chunked updates to the hash which allows you to stream to it, which I make pretty heavy use of. Can we get a similar feature here?

Also, just out of curiosity, what does ipfs use as the default hashing algorithm?

**Comment by diasdavid** [comment]
Hey! 

This module doesn't do the hashing itself, it just handles the prefixing + identifying the hash func. [js-multihashing](https://github.com/multiformats/js-multihashing) and [js-multihashing-async](https://github.com/multiformats/js-multihashing-async) are the ones we use to do the hashing.

We can have a `js-multihashing-stream`. However, do note that WebCrypto doesn't support streaming ([same as encrypt/decrypt..](https://github.com/libp2p/js-libp2p-crypto/issues/30) which means that the hashing would need to use the JS shim which is considerably slower than WebCrypto in the browser.

**Comment by diasdavid** [comment]
IPFS uses by _default for Files_ `sha2-256`, but nowadays it is easy to convert to something else with the use of [CIDs](https://github.com/ipld/js-cid) :)

**Comment by diasdavid** [comment]
@mikeal ping if you still need a Stream API vs the just Async
