### ISSUE TITLE
`buf.length !== len` error when using `ipfs.dag.get`

### ISSUE THREAD

**Issue by JohnAllen** [multiformats/js-multihash#43]
This condition [`buf.length !== len`](https://github.com/multiformats/js-multihash/blob/0bb2bcfa3d6101ab301c63a03ce71292d0e39083/src/index.js#L98) is true for me when calling `ipfs.dag.get('zdpuAyt3vivTZGVtNvoaS2PG6ffdHynokfWA3v52mNVDbjng9')` and the hash is correct, or at least ipfs handles it and it gets pinned and can be retrieved.

Some probably relevant background: I am deconstructing the hashes, storing just the 32 content bytes in Ethereum to save mucho ether gas costs. I deconstruct and reconstruct the hashes using [this code](https://github.com/Distense/distense-ui/blob/master/src/utils.js), and again, the ipfs hashes seem to be valid so I'm not sure if this is a bug or what's the matter here.  Thoughts on what I may be doing wrong or is this a bug?  Oh, I should add that the `len` is 31 and the `buf.length` is 32 when this error throws.

Happy to move this to `js-ipfs` if that's where it should be -- wasn't sure.

**Comment by diasdavid** [comment]
@JohnAllen I'm not sure if I understand the error or how to reproduce it.

**Comment by hugomrdias** [comment]
feel free to re open this if this still happens.
