### ISSUE TITLE
src/index.js as main in package.json

### ISSUE THREAD

**Issue by such** [multiformats/js-multihash#46]
Hey,

Thank you for this package!

I was just wondering if there is a reason why `src/index.js` is configured as the main file instead of `dist/index.js`?
It messes up with webpack that tries to minify `src/index.js` even though it's not ES5.

Thanks!

**Comment by such** [comment]
Actually, webpack does not like `dist/index.js` either. I guess it's because it contains the `let` keyword...

**Comment by such** [comment]
Apparently this is linked to https://github.com/ipfs/aegir/issues/175. Not sure if you want to keep this issue opened...

**Comment by diasdavid** [comment]
Strange that your report is that WebPack doesn't like `let`. Are you trying to use ES5 only code?

//cc @VictorBjelkholm to help here.

**Comment by such** [comment]
Hey,

Here is the explanation that comes with the minification error: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by such** [comment]
By the way I have the same issue with https://github.com/libp2p/js-libp2p-crypto that's built with `aegir` as well, but switching the `main` from `src/index.js` to `dist/index.js` does the trick there.

My workaround is to use `window.require` instead of `import` for now...

**Comment by diasdavid** [comment]
dist/index.js is the _bundle_, that means that it has the code + all of its dependencies shimmed. We want to enable users to create their own bundle so that they can trim unused code and only shim dependencies once.

aegir also uses WebPack for the bundling and minifies it with uglify-es (https://github.com/ipfs/aegir/blob/master/package.json#L81) which supports ES6. You can check our WebPack config at https://github.com/ipfs/aegir/tree/master/src/config

**Comment by such** [comment]
I guess it's pretty hard to provide a library that can be used properly from Node and from the browser. I'm using `create-react-app` and I'd rather not run `eject` to be able to update the webpack config.
It makes a lot of sense that you want to enable users to create their own bundle. But it's not incompatible with transpiling to ES5 in a `lib` directory before publishing and pointing the `main` to `lib/index.js`. Sadly this seems to still be the current guideline for packages on npm.
But that's basically what's proposed in the issue I've linked before and I'd understand if you were not willing to go that way!
Thanks!

**Comment by hugomrdias** [comment]
old issue gonna close this, feel free to reopen
