### ISSUE TITLE
How to detect multihash?

### ISSUE THREAD

**Issue by linonetwo** [multiformats/js-multihash#48]
I want to do something like:

```js
if (isMultihash(someString)) {
  ...
}
```
Can I do this with ```js-multihash```? Like using try catch or so:

```js
try {
  multihash.decode(Buffer(someString));
catch (error) {
  throw new Error(`${someString} is not a multihash`);
}
```

**Comment by lidel** [comment]
Check `multihash` method from [is-ipfs](https://github.com/ipfs/is-ipfs) util, it relies on simple try/catch internally:
- https://github.com/ipfs-shipyard/is-ipfs/blob/c66bb64b02f93e32e426fb4bb8eba03f25a34207/src/index.js#L10-L19

**Comment by linonetwo** [comment]
Thanks, @lidel.
