### ISSUE TITLE
Skein funtion

### ISSUE THREAD

**Issue by DonaldTsang** [multiformats/js-multihash#61]
Something is missing in JS-multihash's algorithm: Skein. 
Partial references:
https://github.com/dashpay/x11-hash-js/blob/master/lib/skein.js
https://github.com/crdrost/sha3-js/blob/master/skein.js
https://github.com/rainersu/hash/blob/master/src/skein.js
https://github.com/thalesfsp/insanehash/blob/master/lib/insanehash.js#L351

**Comment by hugomrdias** [comment]
old issue gonna close this, feel free to reopen
