### ISSUE TITLE
0x0 is called id in go-multihash & identity in js-multihash

### ISSUE THREAD

**Issue by Gozala** [multiformats/js-multihash#70]
JS

https://github.com/multiformats/js-multihash/blob/79b99011c85c520fafa9c493f992ef16cd615dc5/src/constants.js#L6

Go
https://github.com/multiformats/go-multihash/blob/0e239d8fa37b597bd150660e5b6845570aa5b833/multihash.go#L92

Please choose either go or js but have same name across.

**Comment by Stebalien** [comment]
Fixed in go.
