### ISSUE TITLE
remove constants.js size 

### ISSUE THREAD

**Issue by hugomrdias** [multiformats/js-multihash#73]
Any chance we can reduce the size of the constants.js file ?

/cc @vmx @jacobheun

**Comment by vmx** [comment]
js-multicodec could be used, which is a dependency on a lot of things that use js-multihash anyway.

**Comment by hugomrdias** [comment]
that would be perfect what about the codes and sizes ?

**Comment by vmx** [comment]
The codes are part of js-multicodec, the sizes are not (and i also don't find the sizes generally useful. Without checking the code, I would imagine we could just get rid of the default sizes).
