### ISSUE TITLE
Breaking change in patch release

### ISSUE THREAD

**Issue by achingbrain** [multiformats/js-multihash#86]
`v0.4.20` went out with #76 in it which contained a breaking change.

It should have gone out as `v0.5.0`.

`ipld-git` is currently broken as it depends on `~0.4.14` of this module and accesses the `defaultLengths` property from `/src/constants`.

Please can you re-release `0.4.19` as `0.4.21` then release `0.4.20` as `0.5.0`.

**Comment by hugomrdias** [comment]
Done
